import { prisma } from "@/lib/prisma";
import { createSupabaseAdminClient, DOCUMENTS_BUCKET } from "@/lib/supabase/admin";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { randomUUID } from "crypto";

/**
 * Generates a receipt PDF for a payment, uploads it to Supabase Storage,
 * and creates a Document record linked to the unit.
 * Called after payment is recorded (Stripe webhook or manual).
 */
export async function createReceiptDocument(paymentId: string) {
  try {
    const payment = await prisma.paymentStatus.findUnique({
      where: { id: paymentId },
      include: {
        lease: {
          include: {
            tenant: true,
            unit: { include: { property: true } },
          },
        },
      },
    });

    if (!payment || payment.status !== "PAID") return null;

    // Check if receipt document already exists for this payment
    const existing = await prisma.document.findFirst({
      where: {
        type: "RECEIPT",
        linkedEntityId: payment.lease.unit.id,
        filename: { contains: payment.period },
      },
    });
    if (existing) return existing;

    // Format period
    const [year, month] = payment.period.split("-");
    const periodDate = new Date(Number(year), Number(month) - 1);
    const periodLabel = periodDate.toLocaleString("en-US", { month: "long", year: "numeric" });

    const amount = payment.amountPaid
      ? Number(payment.amountPaid)
      : Number(payment.lease.unit.rentAmount);

    // Build PDF
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([612, 792]);
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

    const dark = rgb(0.06, 0.09, 0.16);
    const muted = rgb(0.4, 0.45, 0.55);
    const accent = rgb(0.31, 0.27, 0.9);

    let y = 720;

    page.drawText("PAYMENT RECEIPT", { x: 50, y, font: fontBold, size: 20, color: dark });
    y -= 30;
    page.drawText("Makada Properties", { x: 50, y, font: fontBold, size: 12, color: accent });
    y -= 15;
    page.drawText("303 Lakeview Way, Emerald Hills, CA 94062", { x: 50, y, font, size: 9, color: muted });
    y -= 12;
    page.drawText("Receipt generated " + new Date().toLocaleDateString("en-US"), { x: 50, y, font, size: 9, color: muted });

    y -= 20;
    page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.9, 0.9, 0.9) });

    y -= 35;
    const labelX = 50;
    const valueX = 200;

    const rows = [
      ["Tenant", payment.lease.tenant.fullName],
      ["Property", payment.lease.unit.property.name],
      ["Unit", payment.lease.unit.label],
      ["Period", periodLabel],
      ["Amount", `$${amount.toLocaleString("en-US", { minimumFractionDigits: 2 })}`],
      ["Method", payment.method === "ONLINE" ? "Stripe (Online)" : payment.method === "CHECK" ? "Check" : payment.method === "CASH" ? "Cash" : payment.method || "—"],
      ["Status", payment.status],
      ["Date Paid", payment.paidAt ? new Date(payment.paidAt).toLocaleDateString("en-US") : "—"],
    ];

    for (const [label, value] of rows) {
      page.drawText(label, { x: labelX, y, font, size: 10, color: muted });
      page.drawText(value, { x: valueX, y, font: fontBold, size: 10, color: dark });
      y -= 22;
    }

    if (payment.note) {
      y -= 10;
      page.drawText("Note", { x: labelX, y, font, size: 10, color: muted });
      page.drawText(payment.note, { x: valueX, y, font, size: 10, color: dark });
    }

    y = 80;
    page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.9, 0.9, 0.9) });
    y -= 20;
    page.drawText("This receipt was automatically generated by Makada Properties.", { x: 50, y, font, size: 8, color: muted });
    y -= 12;
    page.drawText(`Payment ID: ${payment.id}`, { x: 50, y, font, size: 8, color: muted });

    const pdfBytes = await pdf.save();

    // Upload to Supabase Storage
    const supabase = createSupabaseAdminClient();
    const tenantName = payment.lease.tenant.fullName.replace(/\s+/g, "-");
    const filename = `receipt-${payment.period}-${tenantName}.pdf`;
    const storagePath = `unit/${payment.lease.unit.id}/${randomUUID()}-${filename}`;

    const { error: uploadError } = await supabase.storage
      .from(DOCUMENTS_BUCKET)
      .upload(storagePath, Buffer.from(pdfBytes), {
        contentType: "application/pdf",
        upsert: false,
      });

    if (uploadError) {
      console.error("Receipt upload error:", uploadError);
      return null;
    }

    // Create Document record
    const doc = await prisma.document.create({
      data: {
        filename,
        fileUrl: "",
        storagePath,
        type: "RECEIPT",
        linkedEntityType: "UNIT",
        linkedEntityId: payment.lease.unit.id,
      },
    });

    console.log(`✅ Receipt document created: ${filename} (${doc.id})`);
    return doc;
  } catch (err) {
    console.error("Failed to create receipt document:", err);
    return null;
  }
}
