import { prisma } from "@/lib/prisma";
import { createSupabaseAdminClient, DOCUMENTS_BUCKET } from "@/lib/supabase/admin";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { randomUUID } from "crypto";

/**
 * Generates a receipt PDF for a fee or deposit payment,
 * uploads it to Supabase Storage, and creates a Document record.
 *
 * For fees:  createFeeReceiptDocument(feeId)
 * For deposits: createFeeReceiptDocument(null, leaseId, "deposit", amount)
 */
export async function createFeeReceiptDocument(
  feeId?: string | null,
  leaseId?: string | null,
  receiptType: "fee" | "deposit" = "fee",
  depositAmount?: number
) {
  try {
    let tenantName: string;
    let propertyName: string;
    let unitLabel: string;
    let unitId: string;
    let itemName: string;
    let amount: number;
    let method: string;
    let paidAt: Date;
    let refId: string;

    if (receiptType === "fee" && feeId) {
      const fee = await prisma.fee.findUnique({
        where: { id: feeId },
        include: {
          lease: {
            include: {
              tenant: true,
              unit: { include: { property: true } },
            },
          },
        },
      });
      if (!fee || fee.paidStatus !== "PAID") return null;

      tenantName = fee.lease.tenant.fullName;
      propertyName = fee.lease.unit.property.name;
      unitLabel = fee.lease.unit.label;
      unitId = fee.lease.unit.id;
      itemName = fee.name;
      amount = fee.paidAmount ? Number(fee.paidAmount) : Number(fee.amount);
      method = fee.paymentMethod === "ONLINE" ? "Stripe (Online)" : fee.paymentMethod === "CHECK" ? "Check" : fee.paymentMethod === "CASH" ? "Cash" : fee.paymentMethod || "—";
      paidAt = fee.paidAt || new Date();
      refId = fee.id;
    } else if (receiptType === "deposit" && leaseId) {
      const lease = await prisma.lease.findUnique({
        where: { id: leaseId },
        include: {
          tenant: true,
          unit: { include: { property: true } },
        },
      });
      if (!lease) return null;

      tenantName = lease.tenant.fullName;
      propertyName = lease.unit.property.name;
      unitLabel = lease.unit.label;
      unitId = lease.unit.id;
      itemName = "Security Deposit";
      amount = depositAmount ?? (lease.depositPaidAmount ? Number(lease.depositPaidAmount) : 0);
      method = lease.depositPaymentMethod === "ONLINE" ? "Stripe (Online)" : lease.depositPaymentMethod === "CHECK" ? "Check" : lease.depositPaymentMethod === "CASH" ? "Cash" : lease.depositPaymentMethod || "—";
      paidAt = lease.depositPaidAt || new Date();
      refId = lease.id;
    } else {
      return null;
    }

    // Build PDF
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([612, 792]);
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

    const dark = rgb(0.06, 0.09, 0.16);
    const muted = rgb(0.4, 0.45, 0.55);
    const accent = rgb(0.31, 0.27, 0.9);

    let y = 720;

    page.drawText("PAYMENT RECEIPT", { x: 50, y, font: fontBold, size: 20, color: dark });
    y -= 30;
    page.drawText("MZAN Capital", { x: 50, y, font: fontBold, size: 12, color: accent });
    y -= 15;
    page.drawText("500 Airport Blvd, Suite 500, Burlingame, CA 94010", { x: 50, y, font, size: 9, color: muted });
    y -= 12;
    page.drawText("Receipt generated " + new Date().toLocaleDateString("en-US"), { x: 50, y, font, size: 9, color: muted });

    y -= 20;
    page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.9, 0.9, 0.9) });

    y -= 35;
    const labelX = 50;
    const valueX = 200;

    const rows: [string, string][] = [
      ["Tenant", tenantName],
      ["Property", propertyName],
      ["Unit", unitLabel],
      ["Item", itemName],
      ["Amount", `$${amount.toLocaleString("en-US", { minimumFractionDigits: 2 })}`],
      ["Method", method],
      ["Status", "PAID"],
      ["Date Paid", paidAt.toLocaleDateString("en-US")],
    ];

    for (const [label, value] of rows) {
      page.drawText(label, { x: labelX, y, font, size: 10, color: muted });
      page.drawText(value, { x: valueX, y, font: fontBold, size: 10, color: dark });
      y -= 22;
    }

    y = 80;
    page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.9, 0.9, 0.9) });
    y -= 20;
    page.drawText("This receipt was automatically generated by MZAN Capital.", { x: 50, y, font, size: 8, color: muted });
    y -= 12;
    page.drawText(`Reference ID: ${refId}`, { x: 50, y, font, size: 8, color: muted });

    const pdfBytes = await pdf.save();

    // Upload to Supabase Storage
    const supabase = createSupabaseAdminClient();
    const safeName = tenantName.replace(/\s+/g, "-");
    const safeItem = itemName.replace(/\s+/g, "-").toLowerCase();
    const dateStr = paidAt.toISOString().slice(0, 10);
    const filename = `receipt-${safeItem}-${dateStr}-${safeName}.pdf`;
    const storagePath = `unit/${unitId}/${randomUUID()}-${filename}`;

    const { error: uploadError } = await supabase.storage
      .from(DOCUMENTS_BUCKET)
      .upload(storagePath, Buffer.from(pdfBytes), {
        contentType: "application/pdf",
        upsert: false,
      });

    if (uploadError) {
      console.error("Fee receipt upload error:", uploadError);
      return null;
    }

    // Create Document record
    const doc = await prisma.document.create({
      data: {
        filename,
        fileUrl: "",
        storagePath,
        type: "RECEIPT",
        linkedEntityType: "UNIT",
        linkedEntityId: unitId,
      },
    });

    console.log(`✅ ${receiptType} receipt created: ${filename} (${doc.id})`);
    return doc;
  } catch (err) {
    console.error("Failed to create fee/deposit receipt:", err);
    return null;
  }
}
