import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

/**
 * GET /api/receipts?paymentId=xxx
 * OR  /api/receipts?leaseId=xxx&period=2026-04
 * Generates a PDF receipt for a payment.
 */
export async function GET(req: NextRequest) {
  const paymentId = req.nextUrl.searchParams.get("paymentId");
  const leaseId = req.nextUrl.searchParams.get("leaseId");
  const period = req.nextUrl.searchParams.get("period");

  let payment;

  if (paymentId) {
    payment = await prisma.paymentStatus.findUnique({
      where: { id: paymentId },
      include: {
        lease: {
          include: {
            tenant: true,
            unit: { include: { property: true } },
          },
        },
      },
    });
  } else if (leaseId && period) {
    payment = await prisma.paymentStatus.findUnique({
      where: { leaseId_period: { leaseId, period } },
      include: {
        lease: {
          include: {
            tenant: true,
            unit: { include: { property: true } },
          },
        },
      },
    });
  } else {
    return NextResponse.json(
      { error: "paymentId or (leaseId + period) is required" },
      { status: 400 }
    );
  }

  if (!payment) {
    return NextResponse.json({ error: "Payment not found" }, { status: 404 });
  }

  if (payment.status !== "PAID") {
    return NextResponse.json({ error: "Receipt is only available for paid payments" }, { status: 400 });
  }

  // Format period
  const [year, month] = payment.period.split("-");
  const periodDate = new Date(Number(year), Number(month) - 1);
  const periodLabel = periodDate.toLocaleString("en-US", { month: "long", year: "numeric" });

  const amount = payment.amountPaid
    ? Number(payment.amountPaid)
    : Number(payment.lease.unit.rentAmount);

  // Build PDF
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]); // Letter size
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const dark = rgb(0.06, 0.09, 0.16);
  const muted = rgb(0.4, 0.45, 0.55);
  const accent = rgb(0.31, 0.27, 0.9);

  let y = 720;

  // Header
  page.drawText("PAYMENT RECEIPT", { x: 50, y, font: fontBold, size: 20, color: dark });
  y -= 30;
  page.drawText("MZAN Capital", { x: 50, y, font: fontBold, size: 12, color: accent });
  y -= 15;
  page.drawText("500 Airport Blvd, Suite 500, Burlingame, CA 94010", { x: 50, y, font, size: 9, color: muted });
  y -= 12;
  page.drawText("Receipt generated " + new Date().toLocaleDateString("en-US"), { x: 50, y, font, size: 9, color: muted });

  // Line
  y -= 20;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.9, 0.9, 0.9) });

  // Details
  y -= 35;
  const labelX = 50;
  const valueX = 200;

  const rows = [
    ["Tenant", payment.lease.tenant.fullName],
    ["Property", payment.lease.unit.property.name],
    ["Unit", payment.lease.unit.label],
    ["Period", periodLabel],
    ["Amount", `$${amount.toLocaleString("en-US", { minimumFractionDigits: 2 })}`],
    ["Method", payment.method === "ONLINE" ? "Stripe (Online)" : payment.method === "CHECK" ? "Check" : payment.method === "CASH" ? "Cash" : payment.method || "—"],
    ["Status", payment.status],
    ["Date Paid", payment.paidAt ? new Date(payment.paidAt).toLocaleDateString("en-US") : "—"],
  ];

  for (const [label, value] of rows) {
    page.drawText(label, { x: labelX, y, font, size: 10, color: muted });
    page.drawText(value, { x: valueX, y, font: fontBold, size: 10, color: dark });
    y -= 22;
  }

  if (payment.note) {
    y -= 10;
    page.drawText("Note", { x: labelX, y, font, size: 10, color: muted });
    page.drawText(payment.note, { x: valueX, y, font, size: 10, color: dark });
  }

  // Footer
  y = 80;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.9, 0.9, 0.9) });
  y -= 20;
  page.drawText("This receipt was automatically generated by MZAN Capital.", { x: 50, y, font, size: 8, color: muted });
  y -= 12;
  page.drawText(`Payment ID: ${payment.id}`, { x: 50, y, font, size: 8, color: muted });

  const pdfBytes = await pdf.save();

  return new NextResponse(Buffer.from(pdfBytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="receipt-${payment.period}-${payment.lease.tenant.fullName.replace(/\s+/g, "-")}.pdf"`,
      "Access-Control-Allow-Origin": "*",
    },
  });
}
